name: Generate RSS

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 mins

jobs:
  gen_rss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: exposures
      - name: Generate RSS
        run: ./gen_rss.py exposures.rss
      - name: Upload RSS
        uses: actions/upload-artifact@v2
        with:
          name: exposures
          path: exposures.rss
