name: Generate RSS

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 mins
  push:
    branches:

jobs:
  gen_rss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get published version
        run: |
          mkdir -p build
          # It is also now in gh-pages branch
          curl -o build/exposures_state.json -f https://kwauchope.github.io/act-covid-rss/exposures_state.json | /bin/true
      # Could set up env var to not bother trying to deploy if don't need to
      - name: Generate RSS
        # If not main could generate based on branch name to keep artifacts
        # set env var blank if main otherwise '_branch'?
        run: |
          ./gen_rss.py build/exposures
      - name: Deploy latest verison
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: build
