name: Generate RSS

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 mins
  push:
    branches:
      - main

jobs:
  gen_rss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate RSS
        run: |
          mkdir -p build
          curl -o build/exposures.rss -f https://kwauchope.github.io/act-covid-rss/exposures.rss | /bin/true
          ./gen_rss.py build/exposures.rss
      - name: Deploy latest verison
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
