name: Generate RSS

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 mins
  push:
    branches:

jobs:
  gen_rss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get published version
        run: |
          git fetch origin gh-pages
          git worktree add build gh-pages
      - name: Generate RSS
        run: |
          if [  ${{ github.ref }} == 'refs/heads/main' ]; then
            PREFIX=exposures
          else
            PREFIX=$(git rev-parse --abbrev-ref HEAD)
          fi
          mkdir -p build/$(dirname ${PREFIX})
          if [  ${{ github.event_name }} == 'push' ]; then
            echo "Push detected, running force build..."
            ./gen_rss.py -f build/${PREFIX}
          else
            echo "Running build..."
            ./gen_rss.py build/${PREFIX}
          fi
      - name: Deploy latest verison
        # Be nice to run only if changes
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
